#### Task 1: Importing Libraries

In [1]:
from keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.preprocessing import image
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import PIL.Image as Image
from skimage import io

In [2]:
url="https://iiif.lib.ncsu.edu/iiif/0052574/full/800,/0/default.jpg"
imge = io.imread(url)
img = imge
x = image.img_to_array(img)
# Reshape the image to (1, img_width, img_height, channels)
x = np.expand_dims(x, axis=0)
print(x)


[[[[ 86. 152. 210.]
   [ 90. 155. 213.]
   [ 92. 157. 215.]
   ...
   [ 50. 115. 181.]
   [ 47. 115. 180.]
   [ 45. 113. 178.]]

  [[ 89. 154. 212.]
   [ 90. 155. 213.]
   [ 90. 155. 213.]
   ...
   [ 49. 114. 178.]
   [ 48. 113. 177.]
   [ 45. 113. 178.]]

  [[ 88. 153. 211.]
   [ 89. 154. 212.]
   [ 88. 153. 211.]
   ...
   [ 48. 114. 175.]
   [ 48. 114. 175.]
   [ 48. 114. 175.]]

  ...

  [[160. 134. 111.]
   [166. 143. 135.]
   [174. 158. 145.]
   ...
   [  0.   0.   0.]
   [  0.   0.   0.]
   [  0.   0.   0.]]

  [[161. 128. 111.]
   [167. 143. 131.]
   [167. 154. 135.]
   ...
   [  0.   0.   0.]
   [  0.   0.   0.]
   [  0.   0.   0.]]

  [[156. 118. 105.]
   [164. 136. 122.]
   [160. 149. 121.]
   ...
   [  0.   0.   0.]
   [  0.   0.   0.]
   [  0.   0.   0.]]]]


In [3]:
# Create an instance of ImageDataGenerator and specify augmentation parameters
datagen = ImageDataGenerator(
        rotation_range=20,
        width_shift_range=0.2,
        height_shift_range=0.2,
        shear_range=0.2,
        zoom_range=0.2,
        horizontal_flip=True,
        fill_mode='nearest')

In [1]:
# Generate augmented images
i = 0
for batch in datagen.flow(x, batch_size=1, save_to_dir='/content/sample_data', save ):
    i += 1
    if i > 40:
        break 

SyntaxError: positional argument follows keyword argument (2125652691.py, line 3)